# Core packages shared by full and minimal macOS profiles.
brew "fd"
brew "gh"
brew "git"
brew "lazygit"
brew "neovim"
brew "node"
brew "python"
brew "ripgrep"
brew "ruff"
brew "shellcheck"
brew "shfmt"
brew "starship"
brew "uv"
brew "zoxide"
